### ISSUE TITLE
slices are not a separate type from exprs

### ISSUE THREAD

**Issue by tjhance** [vinzenz/libpypa#12]
In the official Python grammar,  `Ellipsis`, `Slice`, `ExtSlice`, and `Index` should all be of a type `slice`, not `expr`.

From https://docs.python.org/2/library/ast.html

```
slice = Ellipsis | Slice(expr? lower, expr? upper, expr? step) 
	  | ExtSlice(slice* dims) 
	  | Index(expr value) 
```

Right now pypa has `Ellipsis`, `Slice`, `ExtSlice` and `Index` as expressions rather than having a separate type for slices.

It would probably be better to follow CPython's grammar here - for consistency, and so that one can enforce that the slice of a subscript is, in fact, a slice.

```
expr =
            ...
	     | Subscript(expr value, slice slice, expr_context ctx)
            ...
```

(Note: Pyston currently has the same issue - to properly fix it there, it needs to be fixed here, first.)

**Comment by vinzenz** [comment]
Please note that this will break in its current shape the pyston builds.
