### ISSUE TITLE
Attribute bases shouldn't get a ctx of Store

### ISSUE THREAD

**Issue by kmod** [vinzenz/libpypa#16]
I think for something like `C.x = 1`, pypa is generating an ast Name node for C that has a ctx of Store, whereas CPython uses Load (since the actual C name doesn't get stored to).  I'm not sure how important this behavior is, but we use it in Pyston so it'd be nice if it was the same.

**Comment by kmod** [comment]
I don't understand enough about how pypa works internally to say how, but it looks like this behavior was introduced in f52cb8a960c0621fc835d09629914f266943ae34.

**Comment by vinzenz** [comment]
Yeah this is right, actually C should be load, I have to dig a bit where it doing it, I tried to give it Load, but obviously it didn't apply right

**Comment by vinzenz** [comment]
@kmod Did my early commits fix this? If so I can close this one.
Please let me know.

**Comment by kmod** [comment]
Oh, yeah I believe so, thanks :)
