### ISSUE TITLE
should SyntaxError when assigning to generator expressions

### ISSUE THREAD

**Issue by kmod** [vinzenz/libpypa#43]
Similar to #39; not sure if CPython has a whitelist or a blacklist.

**Comment by kmod** [comment]
(also set comprehensions)

**Comment by undingen** [comment]
We should also raise a syntax error for:
```python
>>> def f(): return lambda x=(yield): 1
... 
  File "<stdin>", line 1
SyntaxError: 'return' with argument inside generator
```

**Comment by vinzenz** [comment]
@kmod well I don't know either, however we can just go for the blacklisting part or now, and it can be transformed to a whitelist, however with the blacklisting way I can at least get to the right error messages

@undingen I think this is actually a different problem, and not related to assignments, we should create an own issue for that IMHO.

**Comment by vinzenz** [comment]
Just a thought: I wonder if the evaluation of that, should be evaluated on 'store' contexts, probably worth considering to refactor to that later on.
