### ISSUE TITLE
Create syntax error for 'return with argument inside generator'

### ISSUE THREAD

**Issue by vinzenz** [vinzenz/libpypa#44]
From: @undingen in #43 
We should also raise a syntax error for:
```python
>>> def f(): return lambda x=(yield): 1
... 
  File "<stdin>", line 1
SyntaxError: 'return' with argument inside generator
```

**Comment by vinzenz** [comment]
@undingen 
After some initial deeper look into this, I think that this actually has to be implemented in pyston itself.
It's a semantic issue, not a parser issue, even if I am already analyzing a lot of those problems in pypa, the problem is that I do not enough context to do those checks. The moment you're transforming the function to a generator due to the yield, you would have to see that there's a return which it must not have.

However this transformation is not done by the parser. Even the CPython ast library doesn't do this.
```python
import ast
ast.parse('def f(): return lambda x=(yield): 1')
```

    >>> import ast
    >>> ast.parse('def f(): return lambda x=(yield): 1')
    <_ast.Module object at 0x7fe61cbeb510>

**Comment by undingen** [comment]
Oh yeah you are right.
I thought cpythons symtable code (which checks for this error) get's run during the AST construction, but didn't check if it's really the case :-(. 
Sorry for inconvenience will fix it inside of pyston.

**Comment by vinzenz** [comment]
hmm, I have a sym table implementation too there, I might have to review if I can do this check.

**Comment by vinzenz** [comment]
interestingly, there's the check already, it's just that it probably didn't see the 'Yield' which is in the default arguments, that might be the reason for it.
